import math
n=float(input("Enter any floating value = "))
sqrtnum = math.sqrt(n)
roundnum = round(n)
ceiling = math.ceil(n)
floornum = math.floor(n)
print(sqrtnum," = Square Root")
print(roundnum," = Rounded Value")
print(ceiling," = Ceiling Value")
print(floornum," = Floor Value")
